server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: EchoAssistant-backend
  datasource:
    url: jdbc:mysql://localhost:3306/echo
    username: root
    password: NXiang2002

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bupt.echoassistantbackend.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: false
    username: abc
    password: 123

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_flag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


# 验证码配置
kaptcha:
  border: "no"             # 是否有边框，默认为 yes，可选 yes、no
  border-color: 105,179,90       # 边框颜色
  text-producer:
    font:
      color: blue          # 验证码字体颜色
      size: 40             # 文本字符大小
      names: 宋体,楷体      # 文本字体样式
    char:
      length: 5          # 验证码文本字符长度
  image:
    width: 120             # 图片宽度
    height: 40             # 图片高度
  session:
    key: code              # 存储 session key

common:
  salt: bupt1234

iflytek:
  host-url: https://ise-api.xfyun.cn/v2/open-ise
  appid: xxxxx
  api:
    key: xxxxx
    secret: xxxxx

#线程池配置
thread-pool-config:
  #核心线程数
  core-pool-size: 5
  #最大线程数
  max-pool-size: 10
  #队列容量
  queue-capacity: 5
  #线程活跃时间,单位秒
  keep-alive-seconds: 60


