server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: EchoAssistant-backend
  datasource:
    url: jdbc:mysql://localhost:3306/echo
    username: ******
    password: ******

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bupt.echoassistantbackend.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: false
    username: abc
    password: 123

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_flag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)